// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CustomOperator_E5M2_to_E2M1(	// src/main/scala/mx/mac/CustomOperator.scala:6:7
  input  [7:0] io_inA,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  input  [3:0] io_inB,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output       io_outSign,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output [6:0] io_outExp,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output [4:0] io_outMant	// src/main/scala/mx/mac/CustomOperator.scala:10:14
);

  wire [5:0] adjExpA = io_inA[6:2] == 5'h0 ? 6'h32 : {1'h0, io_inA[6:2]} - 6'hF;	// src/main/scala/mx/mac/CustomOperator.scala:23:19, :25:29, :35:{20,26}, :37:{26,31}
  wire [2:0] adjExpB = io_inB[2:1] == 2'h0 ? 3'h0 : {1'h0, io_inB[2:1]} - 3'h1;	// src/main/scala/mx/mac/CustomOperator.scala:23:19, :25:29, :37:26, :39:{20,26}, :41:31
  assign io_outSign = io_inA[7] ^ io_inB[3];	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :19:17, :46:23
  assign io_outExp = {adjExpA[5], adjExpA} + {{4{adjExpB[2]}}, adjExpB};	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :35:20, :39:20, :44:25
  assign io_outMant =
    {2'h0, |(io_inA[6:2]), io_inA[1:0]} * {3'h0, |(io_inB[2:1]), io_inB[0]};	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :23:19, :24:19, :25:29, :39:20, :47:27
endmodule

module ScaleAddition_E5M2_to_E2M1_scale_UE8M0(	// src/main/scala/mx/mac/ScaleAddition.scala:10:7
  input         io_inOpSign,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [6:0]  io_inOpExp,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [4:0]  io_inOpMant,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [7:0]  io_inShareScaleA,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
                io_inShareScaleB,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output        io_outSign,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output [11:0] io_outExp,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output [6:0]  io_outMant	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
);

  wire [9:0]  _scaleExpSum_T_2 =
    {2'h0, io_inShareScaleA} + {2'h0, io_inShareScaleB} - 10'hFE;	// src/main/scala/mx/mac/ScaleAddition.scala:47:{36,54}, :51:38
  wire [10:0] ExpAdd =
    {_scaleExpSum_T_2[9], _scaleExpSum_T_2} + {{4{io_inOpExp[6]}}, io_inOpExp};	// src/main/scala/mx/mac/ScaleAddition.scala:47:54, :50:28
  assign io_outSign = io_inOpSign;	// src/main/scala/mx/mac/ScaleAddition.scala:10:7
  assign io_outExp = {ExpAdd[10], ExpAdd};	// src/main/scala/mx/mac/ScaleAddition.scala:10:7, :50:28, :54:14
  assign io_outMant = {2'h0, io_inOpMant};	// src/main/scala/mx/mac/ScaleAddition.scala:10:7, :51:38
endmodule

module ScaleToFP32_E5M2_x_E2M1_UE8M0(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:89:7
  input         io_inSign,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:14
  input  [11:0] io_inExp,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:14
  input  [6:0]  io_inMant,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:14
  output [31:0] io_out	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:14
);

  wire [2:0]  lzc =
    io_inMant[6]
      ? 3'h0
      : io_inMant[5]
          ? 3'h1
          : io_inMant[4]
              ? 3'h2
              : io_inMant[3] ? 3'h3 : io_inMant[2] ? 3'h4 : io_inMant[1] ? 3'h5 : 3'h6;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:109:47
  wire [13:0] shiftedMant = {7'h0, io_inMant} << lzc;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:110:31
  wire [11:0] _adjustedExp_T_4 = io_inExp - {9'h0, lzc} + 12'h82;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:129:{30,41}
  assign io_out =
    {io_inSign,
     $signed(_adjustedExp_T_4) > 12'shFE
       ? 8'hFF
       : $signed(_adjustedExp_T_4) < 12'sh1 ? 8'h0 : _adjustedExp_T_4[7:0],
     shiftedMant[5:0],
     17'h0};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:89:7, :110:31, :120:30, :129:41, :130:33, :131:33, :133:21, :134:{21,63}, :136:16
endmodule

module FP32Adder(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:16:7
  input  [31:0] io_a,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
                io_b,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
  output [31:0] io_out	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
);

  wire [23:0]  valA_M = {|(io_a[30:23]), io_a[22:0]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:24:20, :25:{19,27,36}
  wire [23:0]  valB_M = {|(io_b[30:23]), io_b[22:0]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:28:20, :29:{19,27,36}
  wire [8:0]   _expDiff_T_2 = {1'h0, io_a[30:23]} - {1'h0, io_b[30:23]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:24:20, :28:20, :32:30, :33:26
  wire         aGreater =
    $signed(_expDiff_T_2) > 9'sh0 | _expDiff_T_2 == 9'h0 & valA_M >= valB_M;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :32:30, :33:{26,32,44,52,62}
  wire [23:0]  nearM = aGreater ? valB_M : valA_M;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :33:32, :36:19
  wire [8:0]   absExpDiff = aGreater ? _expDiff_T_2 : 9'h0 - _expDiff_T_2;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:32:30, :33:{26,32,44}, :40:{28,56}
  wire [511:0] _stickyFromAlign_T = 512'h1 << absExpDiff;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:40:28, :44:42
  wire [26:0]  _stickyFromAlign_T_1 = _stickyFromAlign_T[26:0] - 27'h1;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:44:{42,57}
  wire [27:0]  _GEN = {1'h0, aGreater ? valA_M : valB_M, 3'h0};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :33:{26,32}, :37:19, :41:28, :51:27
  wire [27:0]  _GEN_0 = {1'h0, {nearM, 3'h0} >> absExpDiff};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:33:26, :36:19, :40:28, :41:28, :42:33, :51:27
  wire [27:0]  resMag = io_a[31] ^ io_b[31] ? _GEN - _GEN_0 : _GEN + _GEN_0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:23:20, :27:20, :47:23, :49:25, :51:27, :52:12
  wire [4:0]   resLZC =
    resMag[27]
      ? 5'h0
      : resMag[26]
          ? 5'h1
          : resMag[25]
              ? 5'h2
              : resMag[24]
                  ? 5'h3
                  : resMag[23]
                      ? 5'h4
                      : resMag[22]
                          ? 5'h5
                          : resMag[21]
                              ? 5'h6
                              : resMag[20]
                                  ? 5'h7
                                  : resMag[19]
                                      ? 5'h8
                                      : resMag[18]
                                          ? 5'h9
                                          : resMag[17]
                                              ? 5'hA
                                              : resMag[16]
                                                  ? 5'hB
                                                  : resMag[15]
                                                      ? 5'hC
                                                      : resMag[14]
                                                          ? 5'hD
                                                          : resMag[13]
                                                              ? 5'hE
                                                              : resMag[12]
                                                                  ? 5'hF
                                                                  : resMag[11]
                                                                      ? 5'h10
                                                                      : resMag[10]
                                                                          ? 5'h11
                                                                          : resMag[9]
                                                                              ? 5'h12
                                                                              : resMag[8]
                                                                                  ? 5'h13
                                                                                  : resMag[7]
                                                                                      ? 5'h14
                                                                                      : resMag[6]
                                                                                          ? 5'h15
                                                                                          : resMag[5]
                                                                                              ? 5'h16
                                                                                              : resMag[4]
                                                                                                  ? 5'h17
                                                                                                  : resMag[3]
                                                                                                      ? 5'h18
                                                                                                      : resMag[2]
                                                                                                          ? 5'h19
                                                                                                          : {4'hD,
                                                                                                             ~(resMag[1])};	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:49:25, :58:42
  wire [58:0]  normShift = {31'h0, resMag} << resLZC;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:49:25, :59:26
  wire [23:0]  roundedM =
    {1'h0, normShift[26:4]}
    + {23'h0,
       normShift[3]
         & (normShift[4] | normShift[2] | (|(normShift[1:0]))
            | (|(nearM & _stickyFromAlign_T_1[26:3])))};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:33:26, :36:19, :44:{34,57,72}, :59:26, :62:28, :63:28, :64:28, :65:{28,35}, :67:{27,37,53}, :68:25
  assign io_out =
    resMag == 28'h0
      ? 32'h0
      : {aGreater ? io_a[31] : io_b[31],
         (aGreater ? io_a[30:23] : io_b[30:23]) - {{3{resLZC[4]}}, resLZC}
           + {7'h0, roundedM[23]} + 8'h1,
         roundedM[22:0]};	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:16:7, :23:20, :24:20, :27:20, :28:20, :33:32, :35:19, :49:25, :55:20, :68:25, :71:27, :72:27, :73:{31,47,53}, :76:23, :77:{16,39}
endmodule

module BFP_PE(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
  input         clock,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
                reset,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
  input  [31:0] io_op_a_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
  input  [15:0] io_op_b_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
  input  [7:0]  io_share_exp_A_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
                io_share_exp_B_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
  input         io_validIn,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
                io_resetAcc,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
  output        io_validOut,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
  output [31:0] io_accOut	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
);

  wire [31:0] _accAdder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:249:24
  wire [31:0] _reducedSum_nextLevel_adder_2_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
  wire [31:0] _reducedSum_nextLevel_adder_1_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
  wire [31:0] _reducedSum_nextLevel_adder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
  wire [31:0] _conv_3_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
  wire        _sa_3_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [11:0] _sa_3_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [6:0]  _sa_3_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire        _op_3_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [6:0]  _op_3_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [4:0]  _op_3_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [31:0] _conv_2_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
  wire        _sa_2_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [11:0] _sa_2_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [6:0]  _sa_2_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire        _op_2_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [6:0]  _op_2_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [4:0]  _op_2_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [31:0] _conv_1_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
  wire        _sa_1_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [11:0] _sa_1_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [6:0]  _sa_1_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire        _op_1_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [6:0]  _op_1_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [4:0]  _op_1_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [31:0] _conv_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
  wire        _sa_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [11:0] _sa_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire [6:0]  _sa_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
  wire        _op_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [6:0]  _op_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire [4:0]  _op_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
  wire        _asyncRstN_T = ~reset;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:245:20
  reg  [31:0] accReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46
  reg         validReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:247:46
  always @(posedge clock or posedge _asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :245:20
    if (_asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :245:20
      accReg <= 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46
      validReg <= 1'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :247:46
    end
    else begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      if (io_resetAcc)	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
        accReg <= 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46
      else if (io_validIn)	// src/main/scala/mx/mac/FusedDotProductUnit.scala:178:14
        accReg <= _accAdder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46, :249:24
      validReg <= ~io_resetAcc & io_validIn;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:247:46, :253:21, :255:14, :256:26
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      automatic logic [31:0] _RANDOM[0:1];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
        end	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
        accReg = _RANDOM[1'h0];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :246:46
        validReg = _RANDOM[1'h1][0];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :247:46
      `endif // RANDOMIZE_REG_INIT
      if (_asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :245:20
        accReg = 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46
        validReg = 1'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :247:46
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CustomOperator_E5M2_to_E2M1 op (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inA     (io_op_a_i[7:0]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:200:27
    .io_inB     (io_op_b_i[3:0]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:201:27
    .io_outSign (_op_io_outSign),
    .io_outExp  (_op_io_outExp),
    .io_outMant (_op_io_outMant)
  );
  ScaleAddition_E5M2_to_E2M1_scale_UE8M0 sa (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inOpSign      (_op_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpExp       (_op_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpMant      (_op_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_io_outSign),
    .io_outExp        (_sa_io_outExp),
    .io_outMant       (_sa_io_outMant)
  );
  ScaleToFP32_E5M2_x_E2M1_UE8M0 conv (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_inSign (_sa_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inExp  (_sa_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inMant (_sa_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_out    (_conv_io_out)
  );
  CustomOperator_E5M2_to_E2M1 op_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inA     (io_op_a_i[15:8]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:200:27
    .io_inB     (io_op_b_i[7:4]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:201:27
    .io_outSign (_op_1_io_outSign),
    .io_outExp  (_op_1_io_outExp),
    .io_outMant (_op_1_io_outMant)
  );
  ScaleAddition_E5M2_to_E2M1_scale_UE8M0 sa_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inOpSign      (_op_1_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpExp       (_op_1_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpMant      (_op_1_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_1_io_outSign),
    .io_outExp        (_sa_1_io_outExp),
    .io_outMant       (_sa_1_io_outMant)
  );
  ScaleToFP32_E5M2_x_E2M1_UE8M0 conv_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_inSign (_sa_1_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inExp  (_sa_1_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inMant (_sa_1_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_out    (_conv_1_io_out)
  );
  CustomOperator_E5M2_to_E2M1 op_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inA     (io_op_a_i[23:16]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:200:27
    .io_inB     (io_op_b_i[11:8]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:201:27
    .io_outSign (_op_2_io_outSign),
    .io_outExp  (_op_2_io_outExp),
    .io_outMant (_op_2_io_outMant)
  );
  ScaleAddition_E5M2_to_E2M1_scale_UE8M0 sa_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inOpSign      (_op_2_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpExp       (_op_2_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpMant      (_op_2_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_2_io_outSign),
    .io_outExp        (_sa_2_io_outExp),
    .io_outMant       (_sa_2_io_outMant)
  );
  ScaleToFP32_E5M2_x_E2M1_UE8M0 conv_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_inSign (_sa_2_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inExp  (_sa_2_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inMant (_sa_2_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_out    (_conv_2_io_out)
  );
  CustomOperator_E5M2_to_E2M1 op_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inA     (io_op_a_i[31:24]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:200:27
    .io_inB     (io_op_b_i[15:12]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:201:27
    .io_outSign (_op_3_io_outSign),
    .io_outExp  (_op_3_io_outExp),
    .io_outMant (_op_3_io_outMant)
  );
  ScaleAddition_E5M2_to_E2M1_scale_UE8M0 sa_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inOpSign      (_op_3_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpExp       (_op_3_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inOpMant      (_op_3_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:199:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_3_io_outSign),
    .io_outExp        (_sa_3_io_outExp),
    .io_outMant       (_sa_3_io_outMant)
  );
  ScaleToFP32_E5M2_x_E2M1_UE8M0 conv_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_inSign (_sa_3_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inExp  (_sa_3_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_inMant (_sa_3_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:203:20
    .io_out    (_conv_3_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_a   (_conv_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_b   (_conv_1_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_out (_reducedSum_nextLevel_adder_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_a   (_conv_2_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_b   (_conv_3_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:210:22
    .io_out (_reducedSum_nextLevel_adder_1_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_a   (_reducedSum_nextLevel_adder_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_b   (_reducedSum_nextLevel_adder_1_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_out (_reducedSum_nextLevel_adder_2_io_out)
  );
  FP32Adder accAdder (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:249:24
    .io_a   (accReg),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:246:46
    .io_b   (_reducedSum_nextLevel_adder_2_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:228:29
    .io_out (_accAdder_io_out)
  );
  assign io_validOut = validReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :247:46
  assign io_accOut = accReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:165:7, :246:46
endmodule

