// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module CustomOperator_E2M3_to_INT8(	// src/main/scala/mx/mac/CustomOperator.scala:6:7
  input  [5:0]  io_inA,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  input  [7:0]  io_inB,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output        io_outSign,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output [4:0]  io_outExp,	// src/main/scala/mx/mac/CustomOperator.scala:10:14
  output [10:0] io_outMant	// src/main/scala/mx/mac/CustomOperator.scala:10:14
);

  wire [2:0] adjExpA = io_inA[4:3] == 2'h0 ? 3'h0 : {1'h0, io_inA[4:3]} - 3'h1;	// src/main/scala/mx/mac/CustomOperator.scala:23:27, :27:19, :29:29, :38:{20,26}, :40:31
  assign io_outSign = io_inA[5] ^ io_inB[7];	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :19:17, :51:23
  assign io_outExp = {{2{adjExpA[2]}}, adjExpA} - 5'h6;	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :38:20, :49:25
  assign io_outMant =
    {7'h0, |(io_inA[4:3]), io_inA[2:0]}
    * {4'h0, io_inB[7] ? ~(io_inB[6:0]) + 7'h1 : io_inB[6:0]};	// src/main/scala/mx/mac/CustomOperator.scala:6:7, :19:17, :22:20, :23:{21,27}, :24:26, :27:19, :28:19, :29:29, :52:27
endmodule

module ScaleAddition_E2M3_to_INT8_scale_UE5M3(	// src/main/scala/mx/mac/ScaleAddition.scala:10:7
  input         io_inOpSign,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [4:0]  io_inOpExp,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [10:0] io_inOpMant,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  input  [7:0]  io_inShareScaleA,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
                io_inShareScaleB,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output        io_outSign,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output [8:0]  io_outExp,	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
  output [31:0] io_outMant	// src/main/scala/mx/mac/ScaleAddition.scala:14:14
);

  wire [5:0] adjExpScaleA =
    io_inShareScaleA[7:3] == 5'h0 ? 6'h32 : {1'h0, io_inShareScaleA[7:3]} - 6'hF;	// src/main/scala/mx/mac/ScaleAddition.scala:28:17, :33:29, :46:{25,36}, :47:30, :48:{36,41}
  wire [5:0] adjExpScaleB =
    io_inShareScaleB[7:3] == 5'h0 ? 6'h32 : {1'h0, io_inShareScaleB[7:3]} - 6'hF;	// src/main/scala/mx/mac/ScaleAddition.scala:28:17, :33:29, :47:30, :48:36, :49:{25,36}, :51:41
  wire [6:0] scaleExpSum =
    {adjExpScaleA[5], adjExpScaleA} + {adjExpScaleB[5], adjExpScaleB};	// src/main/scala/mx/mac/ScaleAddition.scala:46:25, :49:25, :54:34
  wire [7:0] ExpAdd = {scaleExpSum[6], scaleExpSum} + {{3{io_inOpExp[4]}}, io_inOpExp};	// src/main/scala/mx/mac/ScaleAddition.scala:54:34, :57:28
  assign io_outSign = io_inOpSign;	// src/main/scala/mx/mac/ScaleAddition.scala:10:7
  assign io_outExp = {ExpAdd[7], ExpAdd};	// src/main/scala/mx/mac/ScaleAddition.scala:10:7, :57:28, :61:14
  assign io_outMant =
    {13'h0,
     {11'h0,
      {4'h0, |(io_inShareScaleA[7:3]), io_inShareScaleA[2:0]}
        * {4'h0, |(io_inShareScaleB[7:3]), io_inShareScaleB[2:0]}} * {8'h0, io_inOpMant}};	// src/main/scala/mx/mac/ScaleAddition.scala:10:7, :28:17, :32:20, :33:29, :55:41, :58:38, :62:14
endmodule

module ScaleToFP32_E2M3_x_INT8_UE5M3(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:7
  input         io_inSign,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:97:14
  input  [8:0]  io_inExp,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:97:14
  input  [31:0] io_inMant,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:97:14
  output [31:0] io_out	// src/main/scala/mx/mac/FusedDotProductUnit.scala:97:14
);

  wire [4:0]  lzc =
    io_inMant[31]
      ? 5'h0
      : io_inMant[30]
          ? 5'h1
          : io_inMant[29]
              ? 5'h2
              : io_inMant[28]
                  ? 5'h3
                  : io_inMant[27]
                      ? 5'h4
                      : io_inMant[26]
                          ? 5'h5
                          : io_inMant[25]
                              ? 5'h6
                              : io_inMant[24]
                                  ? 5'h7
                                  : io_inMant[23]
                                      ? 5'h8
                                      : io_inMant[22]
                                          ? 5'h9
                                          : io_inMant[21]
                                              ? 5'hA
                                              : io_inMant[20]
                                                  ? 5'hB
                                                  : io_inMant[19]
                                                      ? 5'hC
                                                      : io_inMant[18]
                                                          ? 5'hD
                                                          : io_inMant[17]
                                                              ? 5'hE
                                                              : io_inMant[16]
                                                                  ? 5'hF
                                                                  : io_inMant[15]
                                                                      ? 5'h10
                                                                      : io_inMant[14]
                                                                          ? 5'h11
                                                                          : io_inMant[13]
                                                                              ? 5'h12
                                                                              : io_inMant[12]
                                                                                  ? 5'h13
                                                                                  : io_inMant[11]
                                                                                      ? 5'h14
                                                                                      : io_inMant[10]
                                                                                          ? 5'h15
                                                                                          : io_inMant[9]
                                                                                              ? 5'h16
                                                                                              : io_inMant[8]
                                                                                                  ? 5'h17
                                                                                                  : io_inMant[7]
                                                                                                      ? 5'h18
                                                                                                      : io_inMant[6]
                                                                                                          ? 5'h19
                                                                                                          : io_inMant[5]
                                                                                                              ? 5'h1A
                                                                                                              : io_inMant[4]
                                                                                                                  ? 5'h1B
                                                                                                                  : io_inMant[3]
                                                                                                                      ? 5'h1C
                                                                                                                      : io_inMant[2]
                                                                                                                          ? 5'h1D
                                                                                                                          : {4'hF,
                                                                                                                             ~(io_inMant[1])};	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:115:47
  wire [62:0] shiftedMant = {31'h0, io_inMant} << lzc;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:116:31
  wire [23:0] roundedM =
    {1'h0, shiftedMant[30:8]}
    + {23'h0, shiftedMant[7] & (shiftedMant[8] | shiftedMant[6] | (|(shiftedMant[5:0])))};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:116:31, :122:31, :126:30, :127:30, :128:30, :129:{30,55}, :131:{28,38,54}, :132:26, :140:33
  wire [8:0]  _adjustedExp_T_8 = io_inExp - {4'h0, lzc} + {8'h0, roundedM[23]} + 9'h95;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:132:26, :134:28, :138:{30,41,53}, :143:21
  wire        isUnderflow = $signed(_adjustedExp_T_8) < 9'sh1;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:138:53, :140:33
  assign io_out =
    io_inMant == 32'h0 | isUnderflow
      ? 32'h0
      : {io_inSign,
         _adjustedExp_T_8 == 9'hFF ? 8'hFF : isUnderflow ? 8'h0 : _adjustedExp_T_8[7:0],
         roundedM[22:0]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:93:7, :112:26, :132:26, :135:28, :138:53, :139:33, :140:33, :142:21, :143:{21,63}, :146:{16,24,54}
endmodule

module FP32Adder(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:16:7
  input  [31:0] io_a,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
                io_b,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
  output [31:0] io_out	// src/main/scala/mx/mac/FusedDotProductUnit.scala:17:14
);

  wire [23:0]  valA_M = {|(io_a[30:23]), io_a[22:0]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:24:20, :25:{19,27,36}
  wire [23:0]  valB_M = {|(io_b[30:23]), io_b[22:0]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:28:20, :29:{19,27,36}
  wire [8:0]   _expDiff_T_2 = {1'h0, io_a[30:23]} - {1'h0, io_b[30:23]};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:24:20, :28:20, :32:30, :33:26
  wire         aGreater =
    $signed(_expDiff_T_2) > 9'sh0 | _expDiff_T_2 == 9'h0 & valA_M >= valB_M;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :32:30, :33:{26,32,44,52,62}
  wire [23:0]  nearM = aGreater ? valB_M : valA_M;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :33:32, :36:19
  wire [8:0]   absExpDiff = aGreater ? _expDiff_T_2 : 9'h0 - _expDiff_T_2;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:32:30, :33:{26,32,44}, :40:{28,56}
  wire [511:0] _stickyFromAlign_T = 512'h1 << absExpDiff;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:40:28, :44:42
  wire [26:0]  _stickyFromAlign_T_1 = _stickyFromAlign_T[26:0] - 27'h1;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:44:{42,57}
  wire [27:0]  _GEN = {1'h0, aGreater ? valA_M : valB_M, 3'h0};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:25:19, :29:19, :33:{26,32}, :37:19, :41:28, :51:27
  wire [27:0]  _GEN_0 = {1'h0, {nearM, 3'h0} >> absExpDiff};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:33:26, :36:19, :40:28, :41:28, :42:33, :51:27
  wire [27:0]  resMag = io_a[31] ^ io_b[31] ? _GEN - _GEN_0 : _GEN + _GEN_0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:23:20, :27:20, :47:23, :49:25, :51:27, :52:12
  wire [4:0]   resLZC =
    resMag[27]
      ? 5'h0
      : resMag[26]
          ? 5'h1
          : resMag[25]
              ? 5'h2
              : resMag[24]
                  ? 5'h3
                  : resMag[23]
                      ? 5'h4
                      : resMag[22]
                          ? 5'h5
                          : resMag[21]
                              ? 5'h6
                              : resMag[20]
                                  ? 5'h7
                                  : resMag[19]
                                      ? 5'h8
                                      : resMag[18]
                                          ? 5'h9
                                          : resMag[17]
                                              ? 5'hA
                                              : resMag[16]
                                                  ? 5'hB
                                                  : resMag[15]
                                                      ? 5'hC
                                                      : resMag[14]
                                                          ? 5'hD
                                                          : resMag[13]
                                                              ? 5'hE
                                                              : resMag[12]
                                                                  ? 5'hF
                                                                  : resMag[11]
                                                                      ? 5'h10
                                                                      : resMag[10]
                                                                          ? 5'h11
                                                                          : resMag[9]
                                                                              ? 5'h12
                                                                              : resMag[8]
                                                                                  ? 5'h13
                                                                                  : resMag[7]
                                                                                      ? 5'h14
                                                                                      : resMag[6]
                                                                                          ? 5'h15
                                                                                          : resMag[5]
                                                                                              ? 5'h16
                                                                                              : resMag[4]
                                                                                                  ? 5'h17
                                                                                                  : resMag[3]
                                                                                                      ? 5'h18
                                                                                                      : resMag[2]
                                                                                                          ? 5'h19
                                                                                                          : {4'hD,
                                                                                                             ~(resMag[1])};	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:49:25, :58:42
  wire [58:0]  normShift = {31'h0, resMag} << resLZC;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:49:25, :59:26
  wire [23:0]  roundedM =
    {1'h0, normShift[26:4]}
    + {23'h0,
       normShift[3]
         & (normShift[4] | normShift[2] | (|(normShift[1:0]))
            | (|(nearM & _stickyFromAlign_T_1[26:3])))};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:33:26, :36:19, :44:{34,57,72}, :59:26, :62:28, :63:28, :64:28, :65:{28,35}, :67:{27,37,53}, :68:25, :80:36
  wire [8:0]   _finalE_wide_T_9 =
    {1'h0, aGreater ? io_a[30:23] : io_b[30:23]} - {{4{resLZC[4]}}, resLZC}
    + {8'h0, roundedM[23]} + 9'h1;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/mx/mac/FusedDotProductUnit.scala:24:20, :25:27, :28:20, :33:{26,32}, :35:19, :68:25, :71:27, :73:{33,49,55}
  assign io_out =
    resMag == 28'h0 | $signed(_finalE_wide_T_9) < 9'sh1
      ? 32'h0
      : {aGreater ? io_a[31] : io_b[31],
         _finalE_wide_T_9 == 9'hFF
           ? 31'h7F800000
           : {_finalE_wide_T_9[7:0], roundedM[22:0]}};	// src/main/scala/mx/mac/FusedDotProductUnit.scala:16:7, :23:20, :27:20, :33:32, :49:25, :55:20, :68:25, :72:27, :73:{49,55}, :76:{30,38,53}, :77:35, :79:16, :80:{17,36}, :81:{36,64}
endmodule

module BFP_PE(	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
  input         clock,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
                reset,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
  input  [23:0] io_op_a_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
  input  [31:0] io_op_b_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
  input  [7:0]  io_share_exp_A_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
                io_share_exp_B_i,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
  input         io_validIn,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
                io_resetAcc,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
  output        io_validOut,	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
  output [31:0] io_accOut	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
);

  wire [31:0] _accAdder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:276:24
  wire [31:0] _reducedSum_nextLevel_adder_2_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
  wire [31:0] _reducedSum_nextLevel_adder_1_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
  wire [31:0] _reducedSum_nextLevel_adder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
  wire [31:0] _conv_3_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
  wire        _sa_3_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [8:0]  _sa_3_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [31:0] _sa_3_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire        _op_3_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [4:0]  _op_3_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [10:0] _op_3_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [31:0] _conv_2_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
  wire        _sa_2_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [8:0]  _sa_2_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [31:0] _sa_2_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire        _op_2_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [4:0]  _op_2_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [10:0] _op_2_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [31:0] _conv_1_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
  wire        _sa_1_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [8:0]  _sa_1_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [31:0] _sa_1_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire        _op_1_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [4:0]  _op_1_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [10:0] _op_1_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [31:0] _conv_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
  wire        _sa_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [8:0]  _sa_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire [31:0] _sa_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
  wire        _op_io_outSign;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [4:0]  _op_io_outExp;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire [10:0] _op_io_outMant;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
  wire        _asyncRstN_T = ~reset;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:272:20
  reg  [31:0] accReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46
  reg         validReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:274:46
  always @(posedge clock or posedge _asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :272:20
    if (_asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :272:20
      accReg <= 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46
      validReg <= 1'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :274:46
    end
    else begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      if (io_resetAcc)	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
        accReg <= 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46
      else if (io_validIn)	// src/main/scala/mx/mac/FusedDotProductUnit.scala:188:14
        accReg <= _accAdder_io_out;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46, :276:24
      validReg <= ~io_resetAcc & io_validIn;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:274:46, :280:21, :282:14, :283:26
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      automatic logic [31:0] _RANDOM[0:1];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
        end	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
        accReg = _RANDOM[1'h0];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :273:46
        validReg = _RANDOM[1'h1][0];	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :274:46
      `endif // RANDOMIZE_REG_INIT
      if (_asyncRstN_T) begin	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :272:20
        accReg = 32'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46
        validReg = 1'h0;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :274:46
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CustomOperator_E2M3_to_INT8 op (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inA     (io_op_a_i[5:0]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:219:27
    .io_inB     (io_op_b_i[7:0]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:220:27
    .io_outSign (_op_io_outSign),
    .io_outExp  (_op_io_outExp),
    .io_outMant (_op_io_outMant)
  );
  ScaleAddition_E2M3_to_INT8_scale_UE5M3 sa (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inOpSign      (_op_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpExp       (_op_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpMant      (_op_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_io_outSign),
    .io_outExp        (_sa_io_outExp),
    .io_outMant       (_sa_io_outMant)
  );
  ScaleToFP32_E2M3_x_INT8_UE5M3 conv (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_inSign (_sa_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inExp  (_sa_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inMant (_sa_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_out    (_conv_io_out)
  );
  CustomOperator_E2M3_to_INT8 op_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inA     (io_op_a_i[11:6]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:219:27
    .io_inB     (io_op_b_i[15:8]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:220:27
    .io_outSign (_op_1_io_outSign),
    .io_outExp  (_op_1_io_outExp),
    .io_outMant (_op_1_io_outMant)
  );
  ScaleAddition_E2M3_to_INT8_scale_UE5M3 sa_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inOpSign      (_op_1_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpExp       (_op_1_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpMant      (_op_1_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_1_io_outSign),
    .io_outExp        (_sa_1_io_outExp),
    .io_outMant       (_sa_1_io_outMant)
  );
  ScaleToFP32_E2M3_x_INT8_UE5M3 conv_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_inSign (_sa_1_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inExp  (_sa_1_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inMant (_sa_1_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_out    (_conv_1_io_out)
  );
  CustomOperator_E2M3_to_INT8 op_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inA     (io_op_a_i[17:12]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:219:27
    .io_inB     (io_op_b_i[23:16]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:220:27
    .io_outSign (_op_2_io_outSign),
    .io_outExp  (_op_2_io_outExp),
    .io_outMant (_op_2_io_outMant)
  );
  ScaleAddition_E2M3_to_INT8_scale_UE5M3 sa_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inOpSign      (_op_2_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpExp       (_op_2_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpMant      (_op_2_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_2_io_outSign),
    .io_outExp        (_sa_2_io_outExp),
    .io_outMant       (_sa_2_io_outMant)
  );
  ScaleToFP32_E2M3_x_INT8_UE5M3 conv_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_inSign (_sa_2_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inExp  (_sa_2_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inMant (_sa_2_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_out    (_conv_2_io_out)
  );
  CustomOperator_E2M3_to_INT8 op_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inA     (io_op_a_i[23:18]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:219:27
    .io_inB     (io_op_b_i[31:24]),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:220:27
    .io_outSign (_op_3_io_outSign),
    .io_outExp  (_op_3_io_outExp),
    .io_outMant (_op_3_io_outMant)
  );
  ScaleAddition_E2M3_to_INT8_scale_UE5M3 sa_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inOpSign      (_op_3_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpExp       (_op_3_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inOpMant      (_op_3_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:218:20
    .io_inShareScaleA (io_share_exp_A_i),
    .io_inShareScaleB (io_share_exp_B_i),
    .io_outSign       (_sa_3_io_outSign),
    .io_outExp        (_sa_3_io_outExp),
    .io_outMant       (_sa_3_io_outMant)
  );
  ScaleToFP32_E2M3_x_INT8_UE5M3 conv_3 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_inSign (_sa_3_io_outSign),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inExp  (_sa_3_io_outExp),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_inMant (_sa_3_io_outMant),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:222:20
    .io_out    (_conv_3_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_a   (_conv_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_b   (_conv_1_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_out (_reducedSum_nextLevel_adder_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder_1 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_a   (_conv_2_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_b   (_conv_3_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:229:22
    .io_out (_reducedSum_nextLevel_adder_1_io_out)
  );
  FP32Adder reducedSum_nextLevel_adder_2 (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_a   (_reducedSum_nextLevel_adder_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_b   (_reducedSum_nextLevel_adder_1_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_out (_reducedSum_nextLevel_adder_2_io_out)
  );
  FP32Adder accAdder (	// src/main/scala/mx/mac/FusedDotProductUnit.scala:276:24
    .io_a   (accReg),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:273:46
    .io_b   (_reducedSum_nextLevel_adder_2_io_out),	// src/main/scala/mx/mac/FusedDotProductUnit.scala:253:29
    .io_out (_accAdder_io_out)
  );
  assign io_validOut = validReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :274:46
  assign io_accOut = accReg;	// src/main/scala/mx/mac/FusedDotProductUnit.scala:175:7, :273:46
endmodule

