// AUTO-GENERATED by orchestrator.py — DO NOT EDIT.
// Adaptor wrapper around Chisel-emitted PE_Array. Re-packs the flat
// scalar Chisel ports (io_op_a_i_0, io_op_a_i_1, …) into packed
// multi-dim arrays expected by snax_mx_alu_shell_wrapper.
// Config: A=fp6_e2m3 B=mxint8 scale=UE4M4 4x16 vec4 blk16 requant_mode=4 (mxint8)
`timescale 1ns / 1ps

module PE_Array_wrapper #(
    parameter int unsigned A_WIDTH     = 6,
    parameter int unsigned B_WIDTH     = 8,
    parameter int unsigned ELEM_WIDTH  = 8,
    parameter int unsigned TileRows    = 4,
    parameter int unsigned TileCols    = 16,
    parameter int unsigned VectorSize  = 4,
    parameter int unsigned BlockSize   = 16,
    parameter int unsigned SCALE_WIDTH = 8
)(
    input  logic clk_i,
    input  logic rst_ni,

    // CSR / control
    input  logic [2:0] A_mode,
    input  logic [2:0] B_mode,
    input  logic [1:0] Result_mode_quan,
    input  logic [1:0] group_size,
    input  logic [3:0] shared_format_i,

    input  logic        acc_reset_i,
    input  logic        send_output_i,
    input  logic [31:0] accumulation_count_i,  // K/vec — runtime threshold
    input  logic        A_valid_i,
    input  logic        B_valid_i,
    output logic        A_ready_o,
    output logic        B_ready_o,

    // Packed operand / shared-exp inputs
    input  logic [0:TileRows-1][A_WIDTH*VectorSize-1:0] op_a_i,
    input  logic [0:TileCols-1][B_WIDTH*VectorSize-1:0] op_b_i,
    input  logic [0:TileRows-1][SCALE_WIDTH-1:0]        shared_exp_A_i,
    input  logic [0:TileCols-1][SCALE_WIDTH-1:0]        shared_exp_B_i,

    // INT8 requantised output: [TileRows][BlockSize][8] packed, plus one 8-bit shared scale per row.
    output logic [0:TileRows-1][7:0]                          shared_scale_out,
    output logic [0:TileRows-1][0:BlockSize-1][ELEM_WIDTH-1:0] result_o,
    output logic                                              valid_out
);

    // Chisel emits positive-asserted reset; shell uses active-low async rst_ni.
    PE_Array u_pe (
        .clock              (clk_i),
        .reset              (rst_ni),
        .io_A_mode          (A_mode),
        .io_B_mode          (B_mode),
        .io_result_mode_quan(Result_mode_quan),
        .io_group_size      (group_size),
        .io_shared_format_i (shared_format_i),
        .io_acc_reset_i         (acc_reset_i),
        .io_send_output_i       (send_output_i),
        .io_accumulation_count_i(accumulation_count_i),
        .io_A_valid_i           (A_valid_i),
        .io_B_valid_i           (B_valid_i),
        .io_A_ready_o           (A_ready_o),
        .io_B_ready_o           (B_ready_o),
        .io_op_a_i_0        (op_a_i[0]),
        .io_op_a_i_1        (op_a_i[1]),
        .io_op_a_i_2        (op_a_i[2]),
        .io_op_a_i_3        (op_a_i[3]),
        .io_op_b_i_0        (op_b_i[0]),
        .io_op_b_i_1        (op_b_i[1]),
        .io_op_b_i_2        (op_b_i[2]),
        .io_op_b_i_3        (op_b_i[3]),
        .io_op_b_i_4        (op_b_i[4]),
        .io_op_b_i_5        (op_b_i[5]),
        .io_op_b_i_6        (op_b_i[6]),
        .io_op_b_i_7        (op_b_i[7]),
        .io_op_b_i_8        (op_b_i[8]),
        .io_op_b_i_9        (op_b_i[9]),
        .io_op_b_i_10        (op_b_i[10]),
        .io_op_b_i_11        (op_b_i[11]),
        .io_op_b_i_12        (op_b_i[12]),
        .io_op_b_i_13        (op_b_i[13]),
        .io_op_b_i_14        (op_b_i[14]),
        .io_op_b_i_15        (op_b_i[15]),
        .io_shared_exp_A_i_0(shared_exp_A_i[0]),
        .io_shared_exp_A_i_1(shared_exp_A_i[1]),
        .io_shared_exp_A_i_2(shared_exp_A_i[2]),
        .io_shared_exp_A_i_3(shared_exp_A_i[3]),
        .io_shared_exp_B_i_0(shared_exp_B_i[0]),
        .io_shared_exp_B_i_1(shared_exp_B_i[1]),
        .io_shared_exp_B_i_2(shared_exp_B_i[2]),
        .io_shared_exp_B_i_3(shared_exp_B_i[3]),
        .io_shared_exp_B_i_4(shared_exp_B_i[4]),
        .io_shared_exp_B_i_5(shared_exp_B_i[5]),
        .io_shared_exp_B_i_6(shared_exp_B_i[6]),
        .io_shared_exp_B_i_7(shared_exp_B_i[7]),
        .io_shared_exp_B_i_8(shared_exp_B_i[8]),
        .io_shared_exp_B_i_9(shared_exp_B_i[9]),
        .io_shared_exp_B_i_10(shared_exp_B_i[10]),
        .io_shared_exp_B_i_11(shared_exp_B_i[11]),
        .io_shared_exp_B_i_12(shared_exp_B_i[12]),
        .io_shared_exp_B_i_13(shared_exp_B_i[13]),
        .io_shared_exp_B_i_14(shared_exp_B_i[14]),
        .io_shared_exp_B_i_15(shared_exp_B_i[15]),
        .io_shared_scale_out(shared_scale_out),
        .io_result          (result_o),
        .io_valid_out       (valid_out)
    );

endmodule
