#!/usr/bin/env python3
"""Generate MXINT8 × E2M1 / UE8M0 test vectors for FusedDotProductUnitTest.

Configuration:
  elementTypeA = MXINT8 (sign-magnitude, implicit scale 2^-6)
  elementTypeB = fp4_e2m1
  scaleType    = UE8M0
  block_size   = 32
  vsize        = 4   → 8 cycles per block
  n_blocks     = 2   → 16 cycles total

Outputs Scala val definitions ready to paste into a test case.
"""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
from quantize import quantize_mx_v2, E2M1, MXINT8

# ── reproductible RNG ──────────────────────────────────────────────────────────
rng = np.random.default_rng(seed=9999)

BLOCK_SIZE = 32
N_BLOCKS   = 2
VSIZE      = 4
variance = 0.001

N = BLOCK_SIZE * N_BLOCKS   # total elements = 64

# Shape: (1, N) — single row so axis=1 gives one scale per block-of-32
raw_a = (rng.normal(0, 2.0, size=(1, N)) * variance).astype(np.float32)
raw_b = (rng.normal(0, 1.5, size=(1, N)) * variance).astype(np.float32)

# ── quantize A as MXINT8, B as fp4_e2m1, scale UE8M0 ─────────────────────────
q_a, scale_shared_a, scale_raw_a, enc_a = quantize_mx_v2(
    raw_a, 'mxint8', BLOCK_SIZE, axis=1, scale_format='UE8M0')

q_b, scale_shared_b, scale_raw_b, enc_b = quantize_mx_v2(
    raw_b, 'fp4_e2m1', BLOCK_SIZE, axis=1, scale_format='UE8M0')

# Flatten to 1-D
enc_a      = enc_a[0].astype(np.uint8)       # shape (N,)
enc_b      = enc_b[0].astype(np.uint8)
scale_raw_a = scale_raw_a[0]                 # shape (n_blocks,)
scale_raw_b = scale_raw_b[0]
scale_f_a   = scale_shared_a[0]
scale_f_b   = scale_shared_b[0]

# ── software golden model ─────────────────────────────────────────────────────
def decode_mxint8(raw: int) -> float:
    """sign-magnitude: bit[7]=sign, bits[6:0]=magnitude; value = ±mag × 2^-6"""
    sign = (raw >> 7) & 1
    mag  = raw & 0x7F
    return (-mag if sign else mag) * (2.0 ** -6)

def decode_ue8m0(raw: int) -> float:
    return 2.0 ** (raw - 127)

def decode_e2m1(raw: int) -> float:
    return E2M1().unpack(raw).to_float()

# Per-block golden sums
golden_per_block = []
for blk in range(N_BLOCKS):
    j0, j1 = blk * BLOCK_SIZE, (blk + 1) * BLOCK_SIZE
    sa = decode_ue8m0(int(scale_raw_a[blk]))
    sb = decode_ue8m0(int(scale_raw_b[blk]))
    dot = 0.0
    for i in range(j0, j1):
        va = decode_mxint8(int(enc_a[i])) * sa
        vb = decode_e2m1(int(enc_b[i]))   * sb
        dot += va * vb
    golden_per_block.append(dot)
golden_total = sum(golden_per_block)

# ── print per-element decode table ───────────────────────────────────────────
print("// " + "="*76)
print("// Auto-generated by gen_int8_e2m1_test.py")
print("// MXINT8 × E2M1 / UE8M0   block_size=32  vsize=4  n_blocks=2")
print("// " + "="*76)
print()

for blk in range(N_BLOCKS):
    j0, j1 = blk * BLOCK_SIZE, (blk + 1) * BLOCK_SIZE
    sa_raw = int(scale_raw_a[blk])
    sb_raw = int(scale_raw_b[blk])
    sa = decode_ue8m0(sa_raw)
    sb = decode_ue8m0(sb_raw)
    maxAbsA = float(np.max(np.abs(raw_a[0, j0:j1])))
    maxAbsB = float(np.max(np.abs(raw_b[0, j0:j1])))
    print(f"// Block {blk}: maxAbsA={maxAbsA:.4f}  maxAbsB={maxAbsB:.4f}")
    print(f"// Block {blk}: scale_A=0x{sa_raw:02X} ({sa:.6e})  scale_B=0x{sb_raw:02X} ({sb:.6e})")
    print(f"// Block {blk}: golden dot = {golden_per_block[blk]:.6f}")
    print(f"// {'Idx':<5} {'rawA':>6} {'decA*sA':>10}   {'rawB':>5} {'decB*sB':>10}   {'A*B':>12}")
    for i in range(j0, j1):
        va = decode_mxint8(int(enc_a[i])) * sa
        vb = decode_e2m1(int(enc_b[i]))   * sb
        print(f"// [{i-j0:2d}]   0x{int(enc_a[i]):02X} {va:>10.4f}   "
              f"0x{int(enc_b[i]):02X} {vb:>10.4f}   {va*vb:>12.4f}")
    print()

print(f"// Total accumulated dot product (2 blocks): {golden_total:.6f}")
print()

# ── Scala val definitions ──────────────────────────────────────────────────────
def scala_seq(name, values, fmt="0x{:02X}", per_line=8):
    """Emit: val name: Seq[Int] = Seq(...)"""
    items = [fmt.format(int(v)) for v in values]
    lines = []
    for i in range(0, len(items), per_line):
        chunk = ", ".join(items[i:i+per_line])
        lines.append(f"      {chunk}")
    body = ",\n".join(lines)
    return f"    val {name}: Seq[Int] = Seq(\n{body})"

print("    // --- paste into Scala test ---")
print()
# Per-block scale raws (one per block)
for blk in range(N_BLOCKS):
    print(f"    val rawScaleA_{blk} = 0x{int(scale_raw_a[blk]):02X}  // scale_A = {decode_ue8m0(int(scale_raw_a[blk])):.6e}")
    print(f"    val rawScaleB_{blk} = 0x{int(scale_raw_b[blk]):02X}  // scale_B = {decode_ue8m0(int(scale_raw_b[blk])):.6e}")
print()

# Per-block element arrays
for blk in range(N_BLOCKS):
    j0, j1 = blk * BLOCK_SIZE, (blk + 1) * BLOCK_SIZE
    print(scala_seq(f"encA_{blk}", enc_a[j0:j1]))
    print(scala_seq(f"encB_{blk}", enc_b[j0:j1]))
    print()

print(f"    // expected accumulated result after both blocks: {golden_total:.6f}f")
